{% set name = "ai21" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ai21-{{ version }}.tar.gz
  sha256: 651515fea7543d5d449e2d9c663b38cad6c3f9cecd6027af5652d1ea508191c7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - typing_extensions >=4.9.0,<5.0.0
    - pydantic >=1.9.0,<3.0.0
    - python >={{ python_min }},<4.0.0
    - ai21-tokenizer >=0.12.0,<1.0.0
    - dataclasses-json >=0.6.3,<0.7.0
    - typing-extensions >=4.9.0,<5.0.0
    - httpx >=0.27.0,<1.0.0
    - tenacity >=8.3.0,<9.0.0
  run_constrained:
    - boto3 >=1.28.82,<2.0.0

test:
  imports:
    - ai21
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: AI21 Python SDK
  home: https://github.com/AI21Labs/ai21-python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
